openapi: '3.0.2'
info:
  title: Project Service 
  description: This service allows for control of the system's projects
  version: '1.0'
  contact:
    name: Jose Francisco Mateo Carrasco
    email: locutermo@gmail.com
servers:
  - url: http://api.projects.sigepro.com

tags:
  - name: Project
    description: Everything about project
        
paths:
  #Modulo de libros  
  /projects:
    get:
      tags:
        - Project      
      summary: Find all projects
            
      operationId: index
      responses:      
        '200':
          $ref: components/responses/responses.yml#/ShowProjects          
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated                     
          
    post:
      tags:
        - Project    
      summary: Add a new project to the system
      operationId: store
      requestBody:
        description: project to add to the system
        content:
          application/json:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ProjectPayload
      responses:      
        '201':
          $ref: components/responses/responses.yml#/ProjectCreated          
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 

  /projects/{id}:
    get:
      tags:
        - Project
      summary: Find a project
      operationId: show
      parameters:
        - $ref: components/parameters/parameters.yml#/id
      responses:
        '200':
          $ref: components/responses/responses.yml#/ShowProject       
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
    put: 
      tags:
        - Project
      summary: Update Project
      operationId: update
      parameters: 
        - $ref: components/parameters/parameters.yml#/id
      requestBody:
        description: project to update to the system
        content:
          x-www-form-urlencoded:
            schema:
              $ref: components/schemas/payloads/payload.yml#/ProjectPayload
      responses:
        '201':
          $ref: components/responses/responses.yml#/ProjectCreated      
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 
        '422':
          $ref: components/responses/responses.yml#/UnprocessableEntity           

    delete:
      tags:
        - Project
      summary: Delete Project
      operationId: destroy
      parameters:
        - $ref: components/parameters/parameters.yml#/id
      responses:
        '200':
          $ref: components/responses/responses.yml#/DeleteProject       
        '404':          
          $ref: components/responses/responses.yml#/NotFound 
        '405':
          $ref: components/responses/responses.yml#/MethodNotAllowed           
        '401':
          $ref: components/responses/responses.yml#/Unauthenticated 


# Aplicar la API key globalmente a todas las operaciones 
security:
  - Authorization: []
            

components:
      
  # SECURITY
  # Contiene todos los tipos de seguridad para el uso del servicio  
  securitySchemes:
    # AUTHORIZATION:
    # Permite el uso del servicio mediante el registro de una api key enviado en el header
    # con el nombre Authorization, por ejemplo: Authorization EJm9IExSA9rv3N9uCVfIhNRdNOMUSe8w
    # estas cadenas serán colocadas en el archivo de configuración del servicio y restringido mediante un middleware
    Authorization:
      type: apiKey
      name: Authorization
      in: header 
